"""Survey response schemas."""
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime
from enum import Enum


class QuestionAnswerCreate(BaseModel):
    """Create question answer."""
    question_id: int
    answer_value: Optional[Any] = None
    media_url: Optional[str] = None
    answered_at: datetime


class SurveyResponseCreate(BaseModel):
    """Create survey response (offline sync)."""
    client_id: str = Field(..., description="UUID generated by mobile app")
    version_id: int
    location: Optional[Dict[str, Any]] = None
    started_at: Optional[datetime] = None
    completed_at: datetime
    device_info: Optional[Dict[str, Any]] = None
    answers: List[QuestionAnswerCreate] = Field(..., min_length=1)


class QuestionAnswerResponse(BaseModel):
    """Question answer response."""
    id: int
    question_id: int
    answer_value: Optional[Any] = None
    media_url: Optional[str] = None
    answered_at: datetime
    
    model_config = ConfigDict(from_attributes=True)


class SurveyResponseDetail(BaseModel):
    """Detailed survey response."""
    id: int
    user_id: int
    version_id: int
    client_id: str
    location: Optional[Dict[str, Any]] = None
    started_at: Optional[datetime] = None
    completed_at: datetime
    synced_at: datetime
    device_info: Optional[Dict[str, Any]] = None
    answers: List[QuestionAnswerResponse] = []
    
    model_config = ConfigDict(from_attributes=True)


class ValidationStatus(str, Enum):
    """Response validation status."""
    SUCCESS = "success"
    SYNCED = "synced"  # Successfully synced from mobile
    PARTIAL = "partial"  # Some answers failed validation
    FAILED = "failed"
    DUPLICATE = "duplicate"


class ResponseValidationResult(BaseModel):
    """Validation result for a single response."""
    client_id: str
    status: ValidationStatus
    response_id: Optional[int] = None  # Only set if success/partial
    message: Optional[str] = None  # Human-readable result description
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)  # For low OCR confidence, etc.


class BatchResponseCreate(BaseModel):
    """Batch create multiple survey responses."""
    responses: List[SurveyResponseCreate] = Field(..., min_length=1, max_length=50)


class BatchResponseResult(BaseModel):
    """Result of batch response submission."""
    total: int
    successful: int
    failed: int
    duplicates: int
    results: List[ResponseValidationResult]
    server_time: datetime
    next_retry_hint: int = Field(
        default=60,
        description="Suggested seconds before next retry for failed items",
    )


class DocumentMetadata(BaseModel):
    """Document metadata for OCR processing."""
    document_type: str = Field(..., description="e.g., 'id_card', 'receipt', 'signature'")
    question_id: Optional[int] = None
    ocr_confidence: Optional[float] = Field(None, ge=0.0, le=1.0)
    ocr_text: Optional[str] = None
    page_number: Optional[int] = None


class DocumentUploadRequest(BaseModel):
    """Document upload request."""
    client_id: str = Field(..., description="Response client_id this document belongs to")
    file_name: str
    file_size: int
    mime_type: str
    metadata: DocumentMetadata


class DocumentUploadResponse(BaseModel):
    """Document upload response — includes Cloudinary signed-upload params."""
    document_id: str
    upload_url: str          # https://api.cloudinary.com/v1_1/<cloud>/image/upload
    expires_at: datetime
    ocr_required: bool = False
    low_confidence_warning: bool = False
    # Signed upload params (mobile sends these directly to Cloudinary)
    cloudinary_signature: Optional[str] = None
    cloudinary_timestamp: Optional[int] = None
    cloudinary_api_key: Optional[str] = None
    cloudinary_public_id: Optional[str] = None
    cloudinary_folder: Optional[str] = None


class SyncStatus(BaseModel):
    """Sync status for mobile app."""
    user_id: int
    pending_responses: int
    synced_responses: int
    pending_documents: int
    last_sync: Optional[datetime] = None
    assigned_surveys: int
    available_updates: List[int] = Field(default_factory=list)  # Survey IDs with new versions
